package Home;

import javax.swing.JOptionPane;
import Home.Login_Form_s;
import static Home.Login_Form_s.User2;
import fantasy_football.*;
import project.Signupnew;
import fantasy_football.Fantasy_Football;
import static fantasy_football.Fantasy_Football.selections;


///*

/**
 *
 * @author Islam
 */

public class sign extends javax.swing.JFrame {
static boolean check =true;

    /**
     * Creates new form sign
     */
    public sign() {
        initComponents();
        Users User2 = new Users();

       }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox15 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Goalkeepers", "Courtois", "Alisson", "Szczesny", "Buffon", "Neuer", "Ter Stegen", "Neto", "Navas", "Ederson", "Oblack", "Kepa" }));
        jComboBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox15ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox15);
        jComboBox15.setBounds(170, 560, 100, 22);

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defenders", "Ramos", "Mendy", "Varane", "Carvajal", "Vazquez", "VanDijk", "Robertson", "Arnold", "Gomez", "Matip", "Bonucci", "DeLigt", "Sandro", "Chellini", "Danilo", "Kimmich", "Hernandez", "Alaba", "Sule", "Boateng", "Pavard", "Davies", "Dest", "Lenglet", "Pique", "Alba", "Roberto", "Kimpembe", "Marquinhos", "Florenzi", "Kurzawa", "Walker", "Cancelo", "Dias", "Stones", "Laporte", "Ake", "Savic", "Gimenez", "Lodi", "Hermoso", "Trippier", "Silva", "Zouma", "Chilwell", "Azpilicueta", " " }));
        jPanel1.add(jComboBox14);
        jComboBox14.setBounds(290, 420, 100, 22);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defenders", "Ramos", "Mendy", "Varane", "Carvajal", "Vazquez", "VanDijk", "Robertson", "Arnold", "Gomez", "Matip", "Bonucci", "DeLigt", "Sandro", "Chellini", "Danilo", "Kimmich", "Hernandez", "Alaba", "Sule", "Boateng", "Pavard", "Davies", "Dest", "Lenglet", "Pique", "Alba", "Roberto", "Kimpembe", "Marquinhos", "Florenzi", "Kurzawa", "Walker", "Cancelo", "Dias", "Stones", "Laporte", "Ake", "Savic", "Gimenez", "Lodi", "Hermoso", "Trippier", "Silva", "Zouma", "Chilwell", "Azpilicueta", " " }));
        jPanel1.add(jComboBox13);
        jComboBox13.setBounds(170, 420, 100, 22);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defenders", "Ramos", "Mendy", "Varane", "Carvajal", "Vazquez", "VanDijk", "Robertson", "Arnold", "Gomez", "Matip", "Bonucci", "DeLigt", "Sandro", "Chellini", "Danilo", "Kimmich", "Hernandez", "Alaba", "Sule", "Boateng", "Pavard", "Davies", "Dest", "Lenglet", "Pique", "Alba", "Roberto", "Kimpembe", "Marquinhos", "Florenzi", "Kurzawa", "Walker", "Cancelo", "Dias", "Stones", "Laporte", "Ake", "Savic", "Gimenez", "Lodi", "Hermoso", "Trippier", "Silva", "Zouma", "Chilwell", "Azpilicueta" }));
        jComboBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox12);
        jComboBox12.setBounds(50, 420, 100, 22);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MidFielders", "Kroos", "Modric", "Casemiro", "Hazard", "Rodrygo", "Valverde", "Salah", "Jota", "Mane", "Fabinho", "Thiago", "Henderson", "Cuadrado", "Bentancur", "Bernardeschi", "Rabiot", "Muller", "Sane", "Koman", "Goretzka", "Gnabry", "Fati", "Coutinho", "Dejong", "Pjanic", "Busquets", "Di Maria", "Pereira", "Herrera", "Verratti", "De Bruyne", "Sterling", "Torres", "Foden", "Gundogan", "Mehrez", "Fernandinho", "Llorente", "Carrasco", "Koke", "Saul", "Correa", "Kante", "Jorginho", "Havertz", "Ziyech", "Kovacic", " " }));
        jPanel1.add(jComboBox11);
        jComboBox11.setBounds(340, 280, 100, 22);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MidFielders", "Kroos", "Modric", "Casemiro", "Hazard", "Rodrygo", "Valverde", "Salah", "Jota", "Mane", "Fabinho", "Thiago", "Henderson", "Cuadrado", "Bentancur", "Bernardeschi", "Rabiot", "Muller", "Sane", "Koman", "Goretzka", "Gnabry", "Fati", "Coutinho", "Dejong", "Pjanic", "Busquets", "Di Maria", "Pereira", "Herrera", "Verratti", "De Bruyne", "Sterling", "Torres", "Foden", "Gundogan", "Mehrez", "Fernandinho", "Llorente", "Carrasco", "Koke", "Saul", "Correa", "Kante", "Jorginho", "Havertz", "Ziyech", "Kovacic", " " }));
        jPanel1.add(jComboBox10);
        jComboBox10.setBounds(230, 280, 100, 22);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Strikers", "Benzema", "Jovic", "Firmino", "Minamino", "Ronaldo", "Morata", "Dybala", "Lewandowski", "Messi", "Dembele", "Griezmann", "Neymar Jr", "Mbappe", "Kean", "Aguero", "Jesus", "Costa", "Suarez", "Felix", "Werner", "Giroud" }));
        jPanel1.add(jComboBox7);
        jComboBox7.setBounds(290, 130, 100, 22);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MidFielders", "Kroos", "Modric", "Casemiro", "Hazard", "Rodrygo", "Valverde", "Salah", "Jota", "Mane", "Fabinho", "Thiago", "Henderson", "Cuadrado", "Bentancur", "Bernardeschi", "Rabiot", "Muller", "Sane", "Koman", "Goretzka", "Gnabry", "Fati", "Coutinho", "Dejong", "Pjanic", "Busquets", "Di Maria", "Pereira", "Herrera", "Verratti", "De Bruyne", "Sterling", "Torres", "Foden", "Gundogan", "Mehrez", "Fernandinho", "Llorente", "Carrasco", "Koke", "Saul", "Correa", "Kante", "Jorginho", "Havertz", "Ziyech", "Kovacic", " " }));
        jPanel1.add(jComboBox9);
        jComboBox9.setBounds(120, 280, 100, 22);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MidFielders", "Kroos", "Modric", "Casemiro", "Hazard", "Rodrygo", "Valverde", "Salah", "Jota", "Mane", "Fabinho", "Thiago", "Henderson", "Cuadrado", "Bentancur", "Bernardeschi", "Rabiot", "Muller", "Sane", "Koman", "Goretzka", "Gnabry", "Fati", "Coutinho", "DeJong", "Pjanic", "Busquets", "Di Maria", "Pereira", "Herrera", "Verratti", "De Bruyne", "Sterling", "Torres", "Foden", "Gundogan", "Mehrez", "Fernandinho", "Llorente", "Carrasco", "Koke", "Saul", "Correa", "Kante", "Jorginho", "Havertz", "Ziyech", "Kovacic" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox8);
        jComboBox8.setBounds(10, 280, 100, 22);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Strikers", "Benzema", "Jovic", "Firmino", "Minamino", "Ronaldo", "Morata", "Dybala", "Lewandowski", "Messi", "Dembele", "Griezmann", "Neymar Jr", "Mbappe", "Kean", "Aguero", "Jesus", "Costa", "Suarez", "Felix", "Werner", "Giroud" }));
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(170, 130, 100, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Strikers", "Benzema", "Jovic", "Firmino", "Minamino", "Ronaldo", "Morata", "Dybala", "Lewandowski", "Messi", "Dembele", "Griezmann", "Neymar Jr", "Mbappe", "Kean", "Aguero", "Jesus", "Costa", "Suarez", "Felix", "Werner", "Giroud" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(50, 130, 100, 22);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/IMG_20210324_185402.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-10, 0, 460, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(345, 0, 470, 600);

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE YOUR TEAM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Team must include 11 players.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Requirments :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Team Can't Contain More Than 3 Players From same Club.");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Captain", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox2.setToolTipText("");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 350, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void jComboBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox15ActionPerformed
        // TODO add your handling code here:
        
      
        
       
     
 
    }//GEN-LAST:event_jComboBox15ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try { 
         for(int i=0;i<126;i++)
        {
            if(jComboBox15.getSelectedItem().toString().equals(Login_Form_s.selections[i].getName())){
            Login_Form_s.User2.Players[0]=Login_Form_s.selections[i];
            break;
            }
            
        }
        
        
        
        for(int i=0;i<126;i++)
        {
            if(jComboBox14.getSelectedItem().toString().equals(Login_Form_s.selections[i].getName())){
            Login_Form_s.User2.Players[1]=Login_Form_s.selections[i];
            break;
            }
            
        }
        
        
        
        for(int i=0;i<126;i++)
        {
            if(jComboBox13.getSelectedItem().toString().equals(Login_Form_s.selections[i].getName())){
            Login_Form_s.User2.Players[2]=Login_Form_s.selections[i];
            break;
            }
            
        }
        
        
        
        for(int i=0;i<126;i++)
        {
            if(jComboBox12.getSelectedItem().toString().equals(Login_Form_s.selections[i].getName())){
            Login_Form_s.User2.Players[3]=Login_Form_s.selections[i];
            break;
            }
            
        }
        
        
        
        for(int i=0;i<126;i++)
        {
            if(jComboBox11.getSelectedItem().toString().equals(Login_Form_s.selections[i].getName())){
            Login_Form_s.User2.Players[4]=Login_Form_s.selections[i];
            break;
            }
            
        }
        
        
        
        for(int i=0;i<126;i++)
        {
            if(jComboBox10.getSelectedItem().toString().equals(Login_Form_s.selections[i].getName())){
            Login_Form_s.User2.Players[5]=Login_Form_s.selections[i];
            break;
            }
            
        }
        
        
        
        for(int i=0;i<126;i++)
        {
            if(jComboBox9.getSelectedItem().toString().equals(Login_Form_s.selections[i].getName())){
            Login_Form_s.User2.Players[6]=Login_Form_s.selections[i];
            break;
            }
            
        }
        
        
        
        for(int i=0;i<126;i++)
        {
            if(jComboBox8.getSelectedItem().toString().equals(Login_Form_s.selections[i].getName())){
            Login_Form_s.User2.Players[7]=Login_Form_s.selections[i];
            break;
            }
            
        }
        
        
        
        for(int i=0;i<126;i++)
        {
            if(jComboBox7.getSelectedItem().toString().equals(Login_Form_s.selections[i].getName())){
            Login_Form_s.User2.Players[8]=Login_Form_s.selections[i];
            break;
            }
            
        }
        
        
        
        for(int i=0;i<126;i++)
        {
            if(jComboBox6.getSelectedItem().toString().equals(Login_Form_s.selections[i].getName())){
            Login_Form_s.User2.Players[9]=Login_Form_s.selections[i];
            break;
            }
            
        }
        
        
        
        for(int i=0;i<126;i++)
        {
            if(jComboBox1.getSelectedItem().toString().equals(Login_Form_s.selections[i].getName())){
            Login_Form_s.User2.Players[10]=Login_Form_s.selections[i];
            break;
            }
        }
        }
        catch (Exception e ){ 
        JOptionPane.showMessageDialog(jPanel2,"Player(s) not selected ");        
        }
        
        if (Login_Form_s.User2.CheckTeam())
       {
            JOptionPane.showMessageDialog(jPanel2,"try again");
       } 
       else
       {
           
           int Totalpoints = User2.getTotal_Points();
           int Averagepoints = Totalpoints/13;
           new Fanatsy(Totalpoints, Averagepoints).setVisible(true);
           
         
        }
        
        
          Login_Form_s.Captain=jComboBox2.getSelectedItem().toString();
                     

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}

